/* global musje */

(function (musje) {
  'use strict';

  /**
   * @class
   * @param {Object} score - plain score object {@link musje.PlainScore}.
   */
  musje.Score = function (score) {
    musje.extend(this, score);
    this.linkTies();

    // console.log(JSON.stringify(this, null, 2))
    // console.log('' + this)
  };

  musje.defineProperties(musje.Score.prototype,
  /** @lends musje.Score.prototype */
  {
    /**
     * Head of the score.
     * @type {musje.ScoreHead}
     */
    head: {
      get: function () {
        return this._head || (this._head = new musje.ScoreHead());
      },
      set: function (head) {
        this._head = new musje.ScoreHead(head);
      }
    },

    /**
     * Partwise parts.
     * - (Getter)
     * - (Setter)
     * @type {musje.PartwiseParts}
     */
    parts: {
      get: function () {
        return this._parts ||
              (this._parts = new musje.PartwiseParts(this));
      },
      set: function (parts) {
        this.parts.length = 0;
        this.parts.addParts(parts);
        this.measures.fromPartwise();
      }
    },

    /**
     * Timewise measures, generated by the initialize function.
     * @type {musje.TimewiseMeasures}
     * @readonly
     */
    measures: {
      get: function () {
        return this._measures ||
              (this._measures = new musje.TimewiseMeasures(this));
      }
    },

    /**
     * Total numbers of measures.
     * @type {number}
     */
    totalMeasures: {
      get: function () {
        return this.measures.length;
      }
    },

    /**
     * Convert score to string.
     * @return {string} Musje source code.
     */
    toString: function () {
      return this.head + this.parts.map(function (part) {
        return part.toString();
      }).join('\n\n');
    },

    toJSON: musje.makeToJSON({
      head: undefined,
      parts: undefined
    }),

    /**
     * A cell is identically a measure in a part or a part in a measure.
     * @param  {Function}
     */
    walkCells: function (callback) {
      this.parts.forEach(function (part, p) {
        part.measures.forEach(function (cell, m) {
          callback(cell, m, p);
        });
      });
    },

    /**
     * Walk each music data.
     * @param  {Function} callback
     */
    walkMusicData: function (callback) {
      this.walkCells(function (cell, m, p) {
        cell.data.forEach(function (data, d) {
          callback(data, d, m, p);
        });
      });
    },

    /**
     * Link ties for each {@link musje.Note} in the entire score.
     */
    linkTies: function () {
      var prevNote = null;

      this.walkMusicData(function (data) {
        var tie;

        if (data.$type === 'Note') {
          tie = data.tie.value;

          if (prevNote) {

            /**
             * Previous tied note. Produced by {@link musje.Score#linkTies}.
             * @memberof musje.Tie#
             * @alias prev
             * @type {(musje.Note|undefined)}
             */
            data.tie.prev = prevNote;

            if (prevNote.pitch.midiNumber !== data.pitch.midiNumber) {

              /**
               * Tie should link to the note with the same pitch.
               * @memberof musje.Tie#
               * @alias error
               * @type {Boolean}
               */
              data.tie.error = true;
              prevNote.tie.error = true;
            }

            /**
             * Next tied note. Produced by {@link musje.Score#linkTies}.
             * @memberof musje.Tie#
             * @alias next
             * @type {(musje.Note|undefined)}
             */
            prevNote.tie.next = data;
          }
          prevNote = tie ? data : null;
        }
      });
    }

  });

}(musje));
