/* global musje */

(function (musje) {
  'use strict';

  /**
   * @class
   * @param {Object} score - plain score object {@link musje.PlainScore}.
   */
  musje.Score = function (score) {
    musje.extend(this, score);

    // console.log(JSON.stringify(this, null, 2))
    // console.log('' + this)
  };

  musje.defineProperties(musje.Score.prototype,
  /** @lends musje.Score.prototype */
  {
    /**
     * Head of the score.
     * @type {musje.ScoreHead}
     */
    head: {
      get: function () {
        return this._head || (this._head = new musje.ScoreHead());
      },
      set: function (head) {
        this._head = new musje.ScoreHead(head);
      }
    },

    /**
     * Partwise parts.
     * - (Getter)
     * - (Setter)
     * @type {musje.PartwiseParts}
     */
    parts: {
      get: function () {
        return this._parts ||
              (this._parts = new musje.PartwiseParts(this));
      },
      set: function (parts) {
        this.parts.removeAll();
        this.parts.addParts(parts);
        this.measures.fromPartwise();
      }
    },

    /**
     * Timewise measures, generated by the initialize function.
     * @type {musje.TimewiseMeasures}
     * @readonly
     */
    measures: {
      get: function () {
        return this._measures ||
              (this._measures = new musje.TimewiseMeasures(this));
      }
    },

    /**
     * Convert score to string.
     * @return {string} Musje source code.
     */
    toString: function () {
      return this.head + this.parts.map(function (part) {
        return part.toString();
      }).join('\n\n');
    },

    toJSON: musje.makeToJSON({
      head: undefined,
      parts: undefined
    }),

    /**
     * A cell is identically a measure in a part or a part in a measure.
     * @param {Function}
     */
    walkCells: function (callback) {
      this.parts.forEach(function (part, p) {
        part.measures.forEach(function (cell, m) {
          callback(cell, m, p);
        });
      });
    },

    /**
     * Walk each music data.
     * @param {Function} callback
     */
    walkMusicData: function (callback) {
      this.walkCells(function (cell, m, p) {
        cell.data.forEach(function (data, d) {
          callback(data, d, m, p);
        });
      });
    }

  });

}(musje));
